# Generated by Django 5.0.6 on 2024-06-07 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=128)),
                ('position', models.CharField(max_length=128)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('contract', models.CharField(choices=[('UOM', 'Umowa o prace')], max_length=3)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='myapp.person')),
            ],
        ),
    ]
